base_config:
  - configs/tts/fs2.yaml
  - configs/singing/base.yaml
  - configs/singing/fs2.yaml
  - configs/singing/speech2singing/base.yaml
processed_long_data_dir: 'data/processed/speech2singing'
processed_short_data_dir: 'data/processed/speech2singing-short'
